swagger: "2.0"
info:
  version: "0.0.2"
  title: "Jace NLP App"
  description: "API to retrieve simply NER entities on English (en), Russian (ru), Ukrainian (uk) languages."
  contact:
    email: "its.an.omen.man@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: localhost:3000
basePath: /
#
tags:
- name: "NER"
  description: "Named-entity recognition (NER)"
#
schemes:
  - https
  - http
consumes:
  - text/plain
  - application/json
produces:
  - application/json
  - application/xml
#
definitions:
  Response:
    required:
      - status
      - data
    properties:
      status:
        type: boolean
      data:
        type: string
  Language:
    type: string
    enum: &LANGUAGE
      - en
      - ru
      - uk
#
parameters:
  lang:
    in: query
    name: lang
    description: "Specify language"
    type: string
    enum: *LANGUAGE
    required: false
  input:
    in: body
    name: text
    description: "Input text"
    required: true
    schema:
      type: string
#


paths:
  /version:
    get:
      tags:
      - "NER"
      summary: "Info"
      description: "Return information about NER services"
      operationId: version
      responses:
        "200":
          description: "Response"
          schema:
            ref: "#/definitions/Response"
  /ner/tokenize:
    post:
      tags:
      - "NER"
      summary: Return tokens from text
      description: "Split string into tokens"
      operationId: tokenize
      parameters:
      - $ref: '#/parameters/lang'
      - in: query
        name: offsets
        description: "Return tuple list of tokens and their positions in text"
        type: boolean
        default: false
      - $ref: '#/parameters/input'
      responses:
        "200":
          description: "Response"
          schema:
            ref: "#/definitions/Response"
  /ner/extract_entities:
    post:
      tags:
      - "NER"
      summary: Return NER entities from text
      description: "Return NER entities from text"
      operationId: extract_entities
      parameters:
      - $ref: '#/parameters/lang'
      - in: query
        name: tags
        description: "Specify tags for retrieving. If this parameter is empty, then all tags will be retrieved. You can see tags for each language with GET /version request."
        type: array
        uniqueItems: true
        items:
          type: string
      - in: query
        name: extract_sentences
        description: "Extracts sentences from text and marks named entities"
        type: boolean
        default: false
      - $ref: '#/parameters/input'
      responses:
        "200":
          description: "Response"
          schema:
            ref: "#/definitions/Response"
  /ner/highlight:
    post:
      tags:
      - "NER"
      summary: Returns NER highlighted html text mapping
      description: "Return html from text"
      operationId: highlight
      consumes:
        - application/json
      parameters:
      - in: query
        name: lang
        description: "Specify language"
        type: string
        enum: *LANGUAGE
        required: false
      - in: query
        name: tags
        description: "Specify tags for retrieving. If this parameter is empty, then all tags will be retrieved. You can see tags for each language with GET /version request."
        type: array
        uniqueItems: true
        items:
          type: string
      - in: body
        name: params
        description: "Specify text for named entities highlights"
        schema:
            type: object
            required:
              - text
            properties:
              text:
                type: string
              htmlTemplate:
                type: string
      responses:
        "200":
          description: "Response"
          schema:
            ref: "#/definitions/Response"
